### Index - listar clientes
GET {{baseUri}}/customers HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Store - criar cliente
POST {{baseUri}}/customers HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Eric Yuri",
    "email": "galo@gmail.com"
}

### Show - buscar cliente
GET {{baseUri}}/customers/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Update - atualizar cliente
PUT {{baseUri}}/customers/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Eric Yuri Atualizado",
    "email": "eric.atualizado@gmail.com"
}

### Destroy - excluir cliente
DELETE {{baseUri}}/customers/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}