### Index - listagem
GET {{baseUri}}/reviews HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Show - consulta de um registro
GET {{baseUri}}/reviews/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Store - criação válida
POST {{baseUri}}/reviews HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "product_id": 1,
    "customer_id": 1,
    "rating": 5,
    "comment": "Produto bom"
}

### Store - criação inválida
POST {{baseUri}}/reviews HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "product_id": 1,
    "customer_id": 1,
    "rating": 8,
    "comment": "Teste de avaliação inválida"
}

### Update
PUT {{baseUri}}/reviews/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "rating": 4,
    "comment": "Avaliação ATUALIZADA via API/REST"
}

### Destroy
DELETE {{baseUri}}/reviews/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}